# Remove wither skulls when chunks are loaded / unloaded to prevent lag
SkullRemover:
  Enabled: true

# disable hoppers at a desired tps
HopperLag:
  Enabled: true
  Disable-Tps: 10.00

# prevents dispensers from dispensing shulker boxes above the specified y-level
# (it would crash the server if you dispensed a shulker above the height limit)
AntiShulkerCrash:
  Enabled: true
  Y-level: 250

# Freezes redstone when the sever tps goes below what you specify
AntiRedstone:
  Enabled: true
  Disable-Tps: 10.00

# Deletes all falling sand blocks on a timer if tps is low enough
# This prevents the brownmen sand lag exploit
# Changing the timer delay requires a full plugin reload to update
AntiFallingSand:
  Enabled: true
  Activate-Tps: 15.00
  Clear-Delay: 10.0